name: lambda
description: mobile core project
version: 0.0.1
author: <Tseegii Tselmeg>


environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.5
  fluttertoast: ^8.0.9
#  flutter_facebook_login: ^3.0.0
  flutter_offline: ^2.1.0
#  firebase_messaging: ^9.0.0
  firebase_core: ^1.19.2
  flutter_spinkit: ^5.1.0
  get: ^4.6.5
  local_auth: ^2.1.2
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.1
  flutter_html: ^2.2.1
  percent_indicator: ^4.2.2
  awesome_dialog: ^2.2.1
  datetime_picker_formfield: 2.0.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  date_format: ^2.0.6
  petitparser: ^5.0.0
  image_picker: ^0.8.5+3
  permission_handler: ^10.0.0
  flutter_echarts: ^2.3.0
  font_awesome_flutter: ^9.0.0
  validators: ^3.0.0
  dropdown_search: ^5.0.2
  provider: ^6.0.3
  geolocator: ^9.0.1
  # flutter_icons: ^1.1.0
  flutter_icons_null_safety: ^1.1.0
  toast: ^0.3.0
  firebase_messaging: ^12.0.0
  flutter_dotenv: ^5.0.2
  flutter_map: ^2.0.0
  flutter_compass: ^0.7.0
  connectivity_plus: ^2.3.6
  flutter_svg: ^0.22.0
  flutter_map_location_marker: ^4.1.3
#  google_sign_in: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
